# Generated by Django 3.1 on 2040-01-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='paid',
            field=models.BooleanField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING')], null=True),
        ),
    ]
