# Generated by Django 3.1 on 2040-01-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20400111_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='paid',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING')], max_length=20, null=True),
        ),
    ]
