# Generated by Django 3.1 on 2023-01-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20400111_0124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
